export const languages = [
    "English",
    "Deutsch",
    "Español",
    "Français",
    "Italiano",
    "Nederlands",
    "Norsk",
    "Polski",
    "Português",
    "Русский",
    "Svenska",
    "日本語",
    "한국어",
    "Türkçe",
    "Dansk",
    "हिन्दी",
    "Čeština",
    "ไทย",
    "Українська",
    "繁體中文",
    "Tiếng Việt",
    "Bahasa Indonesia"
  ]
  